config/routes.rb
SbkObveznici::Application.routes.draw do

  root :to => 'base#index'

  match 'users/login' => 'users#login'
  
  
  resources :users, :only => [:index]  do
    match 'logout'
    get 'new' => 'users#new'
    get 'edit' => 'users#edit'
    post 'create' => 'users#create'
    delete 'destroy' => 'users#destroy'
    put 'update' => 'users#update'
    get 'settings'
    put 'update_settings'

    resources  :search, :only => [:index]
    resources :payers     
    resources :admin, :only => [:index]
    resource :dashboard do
      get :index
    end
  end
end

app/controllers/search_controller.rb
class SearchController < ApplicationController
	def index
		@townships = Township.all
		if query_empty?
			@payers = Payer.all			
		else
			@payers = @user.search_payers(params)
		end
		@results_count = @payers.count
	end

	private

	def query_empty?
		return params[:subject_name].blank? && (params[:township].blank? || params[:township] == 0) && params[:address].blank? && params[:phone].blank? && params[:jmbg].blank? && params[:pdv_payer].blank? ? true : false
	end
end

app/views/search/index.html.erb
<%= form_tag user_search_index_path(@user.id), :method => 'GET' do%>
	<label>Ime i prezime</label>
	<input name="subject_name" type="text" />
	<label>Opstina</label>
	<select name="township">
		<option value="0">Izaberi opstinu</option>
		<% @townships.each do |ts| %>
			<option value="<%=ts.id%>"><%=ts.name%></option>
		<% end %>
	</select>
	<label>Adresa</label>
	<input type="text" name="address" />
	<label>Telefon</label>
	<input type="text" name="phone" />
	<label>JMBG</label>
	<input type="text" name="jmbg" />
	<label>PDV</label>
	<input type="checkbox" name="pdv_payer" />
	<button type="submit">Trazi</button>
<% end %>
<h3>Broj rezultata : <%=@results_count%></h3>
<table>
	<tr>
		<td>Redni broj</td>
		<td>Ime i prezime</td>
		<td>Opstina</td>
		<td>Adresa</td>
		<td>Telefon</td>
		<td>JMBG</td>
		<td>PDV</td>
		<td>Komentar</td>
		<td>Dodao</td>
		<td>Datum dodavanja</td>
	</tr>
	<% @payers.each do |payer| %>
		<tr>
			<td><%= payer.id %></td>
			<td><%= payer.subject_name %></td>
			<td><%= payer.township.name %></td>
			<td><%= payer.address %></td>
			<td><%= payer.phone %></td>
			<td><%= payer.jmbg %></td>
			<td><%= payer.pdv_payer? %></td>
			<td><%= payer.comment %></td>
			<td><%= payer.user.name %></td>
			<td><%= payer.created_at %></td>
		</tr>
	<% end %>
</table>