config/routes.rb
SbkObveznici::Application.routes.draw do

  root :to => 'base#index'

  match 'users/login' => 'users#login'
  
  
  resources :users, :only => [:index]  do
    match 'logout'
    get 'new' => 'users#new'
    get 'edit' => 'users#edit'
    post 'create' => 'users#create'
    delete 'destroy' => 'users#destroy'
    put 'update' => 'users#update'
    get 'settings'
    put 'update_settings'

    resources  :search, :only => [:index]
    resources :payers     
    resources :admin, :only => [:index]
    resource :dashboard do
      get :index
    end
  end
end

app/models/user.rb
class User < ActiveRecord::Base
	attr_accessible :name, :email, :phone, :role, :username, :hash_code
	ROLE_ADMIN 	= 0
	ROLE_MAIN	= 1
	ROLE_BASIC	= 2

	has_many :payers

	# => User CRUD + stuff
	# => Create user (can only be invoked by User::ROLE_ADMIN)
	def create_user(name, username, email, phone, role, password)
		User.create({:name => name, :email => email, :phone => phone, :role => role, :username => username, :hash_code => Digest::SHA256.hexdigest(password)}) if self.is_admin?
	end

	def self.create_admin_user()
		User.create({:name => 'Admin', :email => 'pjanicedin87@gmail.com', :phone => '111111', :role => ROLE_ADMIN, :username => 'admin', :hash_code => Digest::SHA256.hexdigest('obveznici')})
	end
	
	def delete_user(user_id)
		User.destroy(user_id) if self.is_admin?
	end

	# => Administrator edit
	def edit_user(id, name, username, email, phone, role, password)
		user = User.find id
		user.name = name
		user.username = username
		user.email = email
		user.phone = phone
		user.role = role
		user.hash_code = Digest::SHA256.hexdigest(password) unless password.blank?
		user.save
	end
	
	# => User edits for it's self
	def edit_self_user(name, username, email, phone, password)
		self.name = name
		self.username = username
		self.email = email
		self.phone = phone
		self.hash_code = Digest::SHA256.hexdigest(password) unless password.blank?
		self.save
	end

	# => Payer CRUD
	def get_all_payers
		Payer.all
	end

	def create_payer(name, township_id, address, jmbg, pdv_payer, comment, phone)
		payer = Payer.new
		payer.subject_name = name
		payer.township_id = township_id
		payer.address = address
		payer.jmbg = jmbg
		payer.pdv_payer = pdv_payer
		payer.comment = comment
		payer.phone = phone
		payer.user_id = self.id
		payer.save
	end

	def delete_payer(payer_id)
		payer = Payer.find(payer_id)
		payer.destroy if(self.is_admin? || self.id == payer.user_id)
	end

	def edit_payer(payer_id, name, township_id, address, jmbg, pdv_payer, comment, phone)
		payer = Payer.find(payer_id)
		payer.subject_name = name
		payer.township_id = township_id
		payer.address = address
		payer.jmbg = jmbg
		payer.pdv_payer = pdv_payer
		payer.comment = comment
		payer.phone = phone
		payer.save
	end

	# => User checkers
	def is_admin?
		return self.role == ROLE_ADMIN
	end

	def is_viewer?
		return self.role == ROLE_BASIC
	end

	def password_valid?(old_pass)
		return Digest::SHA256.hexdigest(old_pass) == self.hash_code
	end
	# => User roles utils
	def stringify_role
		case self.role
			when ROLE_ADMIN then return 'Administrator'
			when ROLE_MAIN  then return 'Uredjivac'
			when ROLE_BASIC then return 'Pregledavac'
		end
	end

	def get_roles
		return [{:value => 0, :name => 'Administrator'}, {:value => 1, :name => 'Uredjivac'}, {:value => 2, :name => 'Pregledavac'}]
	end

	# => Search
	def search_payers(query_params)
		query = ""
		query += query_params[:township].blank? || query_params[:township] == 0 || query_params[:township] == "0" ?  "" : "township_id = #{query_params[:township]}"
		query += query_params[:subject_name].blank? ?  "" : ' AND subject_name ilike \'%' + query_params[:subject_name] + '%\''
		query += query_params[:address].blank? ?  "" : ' AND address ilike \'%' + query_params[:address] + '%\''
		query += query_params[:jmbg].blank? ?  "" : ' AND jmbg ilike \'%' + query_params[:jmbg] + '%\''
		query += query_params[:phone].blank? ?  "" : ' AND phone ilike \'%' + query_params[:phone] + '%\''
		query += query_params[:pdv_payer].blank? ?  "" : " AND pdv_payer = #{query_params[:pdv_payer] == 'on' ? true : false}"
		puts "--------------------------------------------------------------------------------------------"
		puts "#{query_params}"
		puts "--------------------------------------------------------------------------------------------"
		puts "#{query}"
		puts "--------------------------------------------------------------------------------------------"
		Payer.where(query)
	end

end

app/controllers/users_controller.rb
class UsersController < BaseController
	before_filter :check_user
  layout "application"
  
	def index
	end

	def login
		user = User.find_by_username_and_hash_code(params[:username], Digest::SHA256.hexdigest(params[:password]))
		if user
			session[:id] = user.id
			redirect_to user_dashboard_path(user.id)
		else
			redirect_to root_url({:error => 'Wrong username or password'})
		end
	end

	def logout
    	reset_session
    	session = nil
    	redirect_to root_url()
  	end

  	def new
  		@roles = @user.get_roles
  	end

  	def create
  		@user.create_user(params[:name], params[:username], params[:email], params[:phone], params[:role], params[:password])
  		redirect_to user_admin_index_path(@user.id, {:message => "Uspjesno dodan korisnik #{params[:name]}" })
  	end

  	def destroy
  		@user.delete_user(params[:id])
  		redirect_to user_admin_index_path(@user.id, {:message => "Uspjesno izbrisan korisnik #{params[:name]}" })
  	end

  	def edit
  		@roles = @user.get_roles
  		@editing_user = User.find params[:id]
  	end

  	def update
  		@user.edit_user(params[:id], params[:name], params[:username], params[:email], params[:phone], params[:role], params[:password])
  		redirect_to user_admin_index_path(@user.id, {:message => "Uspjesno izmjenjen korisnik #{params[:name]}" })
  	end

  	def settings

  	end

  	def update_settings
  		if @user.password_valid?(params[:old_pass])
        @user.edit_self_user(params[:name], params[:username], params[:email], params[:phone], params[:new_pass])
        redirect_to user_settings_path(@user.id, {:message => 'Izmjena uspjesna'})
      else
        redirect_to user_settings_path(@user.id, {:message => 'Stara lozinka je neispravna'})
      end
  	end
  	private

  	def check_user
  		@user = User.find(session[:id]) if (@user.nil? && session[:id])
  	end
end

app/views/users/edit.html.erb
<%= form_tag user_update_path(@user.id, {:id => params[:id]}), :method => 'PUT' do |f| %>
	<label>Ime</label>
	<input name="name" type="text" value="<%=@editing_user.name%>" />
	<label>Korisnicko ime</label>
	<input name="username" type="text" value="<%=@editing_user.username%>" />
	<label>Email</label>
	<input type="text" name="email" value="<%=@editing_user.email%>" />
	<label>Telefon</label>
	<input type="text" name="phone" value="<%=@editing_user.phone%>"/>
	<label>Uloga</label>
	<select name="role">
		<% @roles.each do |role| %>
			<option value="<%=role[:value]%>" <%='selected' if @editing_user.role == role[:value] %>><%=role[:name]%></option>
		<% end %>
	</select>
	<label>Lozinka</label>
	<input type="password" name="password" />
	<button type="submit">Snimi</button>
<% end %>

app/views/users/new.html.erb
<%= form_tag user_create_path(@user.id), :method => 'POST' do%>
	<label>Ime</label>
	<input name="name" type="text" />
	<label>Korisnicko ime</label>
	<input name="username" type="text" />
	<label>Email</label>
	<input type="text" name="email" />
	<label>Telefon</label>
	<input type="text" name="phone" />
	<label>Uloga</label>
	<select name="role">
		<% @roles.each do |role| %>
			<option value="<%=role[:value]%>"><%=role[:name]%></option>
		<% end %>
	</select>
	<label>Lozinka</label>
	<input type="password" name="password" />
	<button type="submit">Snimi</button>
<% end %>

app/views/users/settings.html.erb
<%= form_tag user_update_settings_path(@user.id), :method => 'PUT' do %>
	<label>Ime</label>
	<input name="name" type="text" value="<%=@user.name%>" />
	<label>Korisnicko ime</label>
	<input name="username" type="text" value="<%=@user.username%>" />
	<label>Email</label>
	<input type="text" name="email" value="<%=@user.email%>" />
	<label>Telefon</label>
	<input type="text" name="phone" value="<%=@user.phone%>"/>
	<label>Uloga</label>
	<input disabled name="role" value="<%=@user.stringify_role%>" />
	<label>Stara lozinka</label>
	<input type="password" name="old_pass" />
	<label>Nova lozinka</label>
	<input type="password" name="new_pass" />

	<button type="submit">Snimi</button>
<% end %>