config/routes.rb
SbkObveznici::Application.routes.draw do

  root :to => 'base#index'

  match 'users/login' => 'users#login'
  
  
  resources :users, :only => [:index]  do
    match 'logout'
    get 'new' => 'users#new'
    get 'edit' => 'users#edit'
    post 'create' => 'users#create'
    delete 'destroy' => 'users#destroy'
    put 'update' => 'users#update'
    get 'settings'
    put 'update_settings'

    resources  :search, :only => [:index]
    resources :payers     
    resources :admin, :only => [:index]
    resource :dashboard do
      get :index
    end
  end
end

app/models/payer.rb
class Payer < ActiveRecord::Base
	belongs_to :township
	belongs_to :user
	
	def pdv_payer?
		return self.pdv_payer ? 'Da' : 'Ne'
	end
end

app/controllers/payers_controller.rb
class PayersController < ApplicationController
	
	def new
		@townships = Township.all
	end

	def create
		@user.create_payer(params[:subject_name], params[:township], params[:address], params[:jmbg], params[:pdv_payer], params[:comment], params[:phone])
		redirect_to user_dashboard_path(@user.id)
	end

	def destroy
		@user.delete_payer(params[:id])
		redirect_to user_dashboard_path(@user.id, {:message => 'Korisnik uspjesno obrisan'})
	end

	def edit
		@townships = Township.all
		@payer = Payer.find(params[:id])
	end

	def update
		@user.edit_payer(params[:id], params[:subject_name], params[:township], params[:address], params[:jmbg], params[:pdv_payer], params[:comment], params[:phone])
		redirect_to user_dashboard_path(@user.id, {:message => 'Korisnik uspjesno izmjenjen'})
	end
end

app/views/payers/edit.html.erb
<%= form_tag user_payer_path(@user.id), :method => 'PUT' do%>
	<label>Ime i prezime</label>
	<input name="subject_name" type="text" value="<%=@payer.subject_name%>"/>
	<label>Opstina</label>
	<select name="township">
		<% @townships.each do |ts| %>

			<option value="<%=ts.id%>" <%= 'selected' if ts.id == @payer.township %>><%=ts.name%></option>
		<% end %>
	</select>
	<label>Adresa</label>
	<input type="text" name="address" value="<%=@payer.address %>"/>
	<label>Telefon</label>
	<input type="text" name="phone" value="<%=@payer.phone %>"/>
	<label>JMBG</label>
	<input type="text" name="jmbg" value="<%=@payer.jmbg %>"/>
	<label>PDV</label>
	<input type="checkbox" name="pdv_payer" <%='checked' if @payer.pdv_payer%> />
	<textarea name="comment"><%=@payer.comment%></textarea>
	<button type="submit">Snimi</button>
<% end %>

app/views/payers/new.html.erb
<%= form_tag user_payers_path(@user.id), :method => 'POST' do%>
	<label>Ime i prezime</label>
	<input name="subject_name" type="text" />
	<label>Opstina</label>
	<select name="township">
		<% @townships.each do |ts| %>
			<option value="<%=ts.id%>"><%=ts.name%></option>
		<% end %>
	</select>
	<label>Adresa</label>
	<input type="text" name="address" />
	<label>Telefon</label>
	<input type="text" name="phone" />
	<label>JMBG</label>
	<input type="text" name="jmbg" />
	<label>PDV</label>
	<input type="checkbox" name="pdv_payer" />
	<textarea name="comment"></textarea>
	<button type="submit">Snimi</button>
<% end %>