config/routes.rb
SbkObveznici::Application.routes.draw do

  root :to => 'base#index'

  match 'users/login' => 'users#login'
  
  
  resources :users, :only => [:index]  do
    match 'logout'
    get 'new' => 'users#new'
    get 'edit' => 'users#edit'
    post 'create' => 'users#create'
    delete 'destroy' => 'users#destroy'
    put 'update' => 'users#update'
    get 'settings'
    put 'update_settings'

    resources  :search, :only => [:index]
    resources :payers     
    resources :admin, :only => [:index]
    resource :dashboard do
      get :index
    end
  end
end

app/controllers/dashboards_controller.rb
class DashboardsController < ApplicationController
	def index
		@payers = @user.get_all_payers
	end
end

app/views/dashboards/index.html.erb
<table>
	<tr>
		<td>Redni broj</td>
		<td>Ime i prezime</td>
		<td>Opstina</td>
		<td>Adresa</td>
		<td>Telefon</td>
		<td>JMBG</td>
		<td>PDV</td>
		<td>Komentar</td>
		<td>Dodao</td>
		<td>Datum dodavanja</td>
		<td>Izbrisi</td>
		<td>Izmjeni</td>
	</tr>
	<% @payers.each do |payer| %>
		<tr>
			<td><%= payer.id %></td>
			<td><%= payer.subject_name %></td>
			<td><%= payer.township.name %></td>
			<td><%= payer.address %></td>
			<td><%= payer.phone %></td>
			<td><%= payer.jmbg %></td>
			<td><%= payer.pdv_payer? %></td>
			<td><%= payer.comment %></td>
			<td><%= payer.user.name %></td>
			<td><%= payer.created_at %></td>
			<td><%= link_to('Izbrisi', user_payer_path(@user.id, payer.id), :method => 'DELETE', :confirm => 'Da li ste sigurni?') 			if (@user.id == payer.user_id || @user.is_admin?) %></td>
			<td><%= link_to('Izmjeni', edit_user_payer_path(@user.id, payer.id)) 															if (@user.id == payer.user_id || @user.is_admin?) %></td>
		</tr>
	<% end %>
</table>
<%= link_to  "Dodaj novog obveznika", new_user_payer_path(@user.id) unless @user.is_viewer? %>